name: CourseWork CI Actions
run-name: ${{ github.actor }} is making changes
on: [push]
jobs:
  Linting-Project:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:      
      - uses: actions/checkout@v3
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installing modules
        run: npm install
      - name: Linting project
        run: npm run lint 