name: CourseWork CI Actions
run-name: ${{ github.actor }} is making changes
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  TestingProject:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    services:
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: postgres

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installing modules
        run: npm install
      - name: Running Prettier
        run: npm run pretty
      - name: Running Eslint
        run: npm run lint
      - name: Run Unit Tests
        run: npm run test
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB_NAME: postgres
      - name: Building Project
        run: npm run build
